#!/usr/bin/env bash

project=$(basename $(pwd))
commit_hash=$(git rev-parse --short HEAD)
osascript -e "display notification \"Starting build - commit $commit_hash\" with title \"$project\""

build_home=/home/gradle

docker run --rm \
  --volume=$PWD:$build_home/project \
  --volume=$HOME/.gradle:$build_home/.gradle \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  gradle:jdk11 \
  /bin/bash -c "git clone --depth=1 file://$build_home/project isolated-project && gradle build -p isolated-project --console=plain"

docker_exit_status=$?

if [ $docker_exit_status -eq 0 ]; then
    osascript -e "display notification \"Build successful - commit $commit_hash\" with title \"$project\" sound name \"Submarine\""
else
    osascript -e "display notification \"Build failed - commit $commit_hash\" with title \"$project\" sound name \"Submarine\""
fi

exit $docker_exit_status

    



